name: Build and sign multi-arch container

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'Makefile.test'
      - 'scripts/**'
      - 'docs/**'
      - 'examples/**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Build schema bundle for kubeconform
      run: |
        scripts/source-schemas.sh

    - name: Build containers
      run: make all-container

    - name: Log in to the Container registry
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push containers
      run: make manifest-list | tee manifest.log

    - uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # tag=v3.8.1

    - name: Sign container
      run: make manifest-list-sign
