name: Build and sign multi-arch container

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'Makefile.test'
      - 'catalog.json'
      - 'scripts/**'
      - 'docs/**'
      - 'examples/**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Build schema bundle for kubeconform
      run: |
        scripts/source-schemas.sh

    - name: Build containers
      run: make all-container

    - name: Log in to the Container registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push containers
      run: make manifest-list | tee manifest.log

    - uses: sigstore/cosign-installer@3454372f43399081ed03b604cb2d021dabca52bb # tag=v3.8.2

    - name: Sign container
      run: make manifest-list-sign
