name: Run tests

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'scripts/**'
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install devbox
      uses: jetify-com/devbox-install-action@22b0f5500b14df4ea357ce673fbd4ced940ed6a1 # v0.13.0

    - name: build local binaries for test
      run: devbox run -- make build lint test

    - name: code tests
      run: make test GOFLAGS="-v"

    - name: e2e tests
      run: devbox run -- make e2e-tests
